version: '3.8'

services:
  webapi:
    container_name: webapi
    build: 
      context: ./Example1
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: go run cmd/routes.go cmd/main.go -b 0.0.0.0
  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: