version: '3.8'

services:
  api1:
    container_name: api1
    build: 
      context: ./Example1
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 3000:3000
    command: go run cmd/routes.go cmd/main.go -b 0.0.0.0

  api2:
    container_name: api2
    build:
      context: ./Example2
    ports:
      - 8080:8080

  db:
    container_name: db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: